-- MySQL Script generated by MySQL Workbench
-- 04/30/17 14:20:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema convenia_api
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema convenia_api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `convenia_api` DEFAULT CHARACTER SET utf8 ;
USE `convenia_api` ;

-- -----------------------------------------------------
-- Table `convenia_api`.`cn_seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `convenia_api`.`cn_seller` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `convenia_api`.`cn_sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `convenia_api`.`cn_sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` FLOAT(6,2) NOT NULL,
  `comission` FLOAT(6,2) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `seller_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_seller_id_sales_idx` (`seller_id` ASC),
  CONSTRAINT `fk_seller_id_sales`
    FOREIGN KEY (`seller_id`)
    REFERENCES `convenia_api`.`cn_seller` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
